.PHONY: clean All

All:
	@echo "----------Building project:[ Prueba - Debug ]----------"
	@cd "Prueba" && "$(MAKE)" -f  "Prueba.mk"
clean:
	@echo "----------Cleaning project:[ Prueba - Debug ]----------"
	@cd "Prueba" && "$(MAKE)" -f  "Prueba.mk" clean
